version: '3.7'

volumes:
    # prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  db: 
    image: postgres 
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports: 
      - "5432:5432"
    networks:
      - back-tier
      
  adminer: 
    image: adminer 
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier
      - front-tier

    # prometheus:
    #   image: prom/prometheus
    #   volumes:
    #     - ./evidently_service/config/prometheus.yml:/etc/prometheus/prometheus.yml
    #     - prometheus_data:/prometheus
    #   command:
    #     - '--config.file=/etc/prometheus/prometheus.yml'
    #     - '--storage.tsdb.path=/prometheus'
    #   ports:
    #     - "9091:9090"
    #   networks:
    #     - back-tier
    #   restart: always

  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - "3000:3000"
    # volumes:
    #   - ./g/config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    networks:
      - back-tier
      - front-tier
    restart: always
