channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.1.2
- pip:
  - mlflow<3,>=2.3
  - numpy==1.25.0
  - packaging==23.0
  - pandas==1.5.3
  - psutil==5.9.0
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - typing-extensions==4.7.1
  - xgboost==1.7.6
name: mlflow-env
