# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
# datasources:
#   - name: Prometheus
#     type: prometheus
#     access: proxy
#     url: http://prometheus.:9090  

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: test 
    user: postgres
    secureJsonData:
      - password: 'example'
    JsonData:
      sslmode: 'disable'